version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
    - appspec.yml
  secondary-artifacts:
    messageUtil_jar:
      files:
        - target/messageUtil-1.0.jar
        - appspec.yml
      name: messageUtil_jar